kind: pipeline
name: Dronerino

steps:
- name: build
  image: ubuntu:xenial
  commands:
  - apt-get install sudo git -y
  - git clone git://github.com/akhilnarang/scripts
  - cd scripts
  - bash setup/android_build_env.sh
