kind: pipeline
name: Dronerino

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - apt-get update
  - apt-get install sudo make git -y
  - git clone git://github.com/akhilnarang/scripts
  - cd scripts
  - bash setup/android_build_env.sh
