kind: pipeline
name: Dronerino

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - apt-get update
  - apt-get install wget sudo make git repo -y
  - sudo wget https://raw.githubusercontent.com/Fornax96/pdup/master/pdup -O "/usr/local/bin/pdup"; sudo chmod +x "/usr/local/bin/pdup"
  - git config --global user.name "Luke Williams"
  - git config --global user.email "luke@turbox.uk"
  - git clone git://github.com/akhilnarang/scripts
  - cd scripts
  - bash setup/android_build_env.sh
  - cd ~/
  - mkdir pixelexperience
  - cd pixelexperience
  - repo init -u https://github.com/PixelExperience/manifest -b pie
  - mkdir .repo/local_manifests
  - cd .repo/local_manifests
  - wget https://gitlab.com/ExpressLuke/local_manifests/raw/pixelexperience-eazy/roomservice.xml
  - cd ~/pixelexperience
  - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
  - lunch aosp_hero2lte-userdebug && mka bacon -j$(nproc --all)
  - EDGE=$(pdup ~/pixelexperience/out/target/product/hero2lte/PixelExperience_hero2lte*.zip | egrep -o 'https?://[^ ]+')
  - lunch aosp_herolte-userdebug && mka bacon -j$(nproc --all)
  - FLAT=$(pdup ~/pixelexperience/out/target/product/hero2lte/PixelExperience_herolte*.zip | egrep -o 'https?://[^ ]+')
  - echo Edge link
  - echo --
  - echo ${EDGE}
  - echo .
  - echo Flat link
  - echo --
  - echo ${FLAT}
